altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  39314dfe-cca1-41f2-84dd-002b705ceac4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-05T20:32:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 41b5b8c7-5638-4486-b93d-732d4d9e454c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0488e69-6838-40ed-b1ef-d5eb4baafc01
        userCondition: null
fs: local
handle: uploads
name: Uploads
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: local
transformSubpath: __transforms__
